CREATE DATABASE IF NOT EXISTS MOVIES;
USE DATABASE MOVIES;
SELECT * FROM MOVIES;

USE ROLE ORGADMIN;

SELECT * FROM movies;

SHOW SCHEMAS;

SHOW TABLES;

SELECT * FROM TABLE.CUSTOMER;
USE WAREHOUSE COMPUTE_WH;

DROP DATABASE MOVIES;

USE ROLE ACCOUNTADMIN;