dbt_code:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: zc67815.west-europe.azure
      user: sermedsm4
      password: Realjuve134
      role: ACCOUNTADMIN
      database: sermedms4
      warehouse: dev_wh
      schema: PUBLIC
      threads: 4
      client_session_keep_alive: False
